# This is a basic workflow to help you get started with Actions

name: Publish Nuget Packages

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.0
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Publish 11Binary.Mercury.Shared.dll
      uses: brandedoutcast/publish-nuget@v2.5.2
      with:
          PROJECT_FILE_PATH: /11Binary.Mercury.Shared.csproj
          NUGET_KEY: ${{oy2otycocjv7gchsxb5qng5fp2i3exjenjpu6n7q5kzp24}}
